### ISSUE TITLE
[Solved] "Models aren't loaded yet" na primeira execução

### ISSUE THREAD

**Issue by tiagobugarin** [hacklabr/iddacultura-provider#1]
Ao executar pela primeira vez o comando:

> ./manage.py syncdb

o seguinte output acontece:
`
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/registration/models.py", line 15, in <module>
    User = get_user_model()
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/var/www/iddacultura-provider-env/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
`

Estou tentando instalar em um Debian Jessie. Selecionei sqlite3 como db inicialmente.

Alguma ajuda ?!

**Comment by tiagobugarin** [comment]
Aparentemente o problema acontece quando se instala a versão mais recente do distribute na linha:

> easy_install -U distribute

Substituindo essa linha por:

> easy_install distribute==0.6.30

o problema não ocorre.
Usei essa versão do distribute porque é a versão que está listada no arquivo dependencies.txt.
